import type { Metadata } from 'next';

import './theme-config.css';
import './globals.css';
import NavBar from './NavBar';
import '@radix-ui/themes/styles.css';
import { Theme, ThemePanel } from '@radix-ui/themes';
import { Inter } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <Theme accentColor="orange" grayColor="gray" appearance="dark">
          <NavBar></NavBar>
          <main className="p-5">{children}</main>
        </Theme>
      </body>
    </html>
  );
}
